name = "MasterTask"
uuid = "ddb8c566-1a87-45d0-ac7d-58b9aec67b2a"
authors = ["GjermundOL <gol1994@gmail.com>"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Muscade = "93488820-1883-11ed-0c34-05177b029e4d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
